# Generated by Django 5.2.6 on 2025-11-01 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tail_number", models.CharField(max_length=20, unique=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AircraftType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "energy_type",
                    models.CharField(
                        choices=[("ELECTRIC", "Electric"), ("FUEL", "Fuel")],
                        default="ELECTRIC",
                        max_length=10,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("EVTOL", "Evtol"),
                            ("DRONE", "Drone"),
                            ("HELICOPTER", "Helicopter"),
                        ],
                        default="EVTOL",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AircraftData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("energy_level", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="monitor.aircraft",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aircraft",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircrafts",
                to="monitor.aircrafttype",
            ),
        ),
    ]
