# Generated by Django 5.2.6 on 2025-11-06 13:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_route_flightinstance_tracking_waypoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vertiport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vertiport_code", models.CharField(max_length=50)),
                ("vertiport_name", models.CharField(max_length=100)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name="flightinstance",
            old_name="end_time",
            new_name="scheduled_arrival_datetime",
        ),
        migrations.RenameField(
            model_name="flightinstance",
            old_name="start_time",
            new_name="scheduled_departure_datetime",
        ),
        migrations.AddField(
            model_name="flightinstance",
            name="callsign",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft_type_aircrafts",
                to="monitor.aircrafttype",
            ),
        ),
        migrations.AlterField(
            model_name="aircraftdata",
            name="aircraft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft_aircraft_data",
                to="monitor.aircraft",
            ),
        ),
        migrations.AlterField(
            model_name="aircraftdata",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="flightinstance",
            name="aircraft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft_flight_instances",
                to="monitor.aircraft",
            ),
        ),
        migrations.AlterField(
            model_name="flightinstance",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="route_flight_instances",
                to="monitor.route",
            ),
        ),
        migrations.AlterField(
            model_name="tracking",
            name="flight_instance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_instance_tracking",
                to="monitor.flightinstance",
            ),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_waypoints",
                to="monitor.route",
            ),
        ),
        migrations.AddField(
            model_name="flightinstance",
            name="arrival_vertiport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="arrival_vertiport_flight_instances",
                to="monitor.vertiport",
            ),
        ),
        migrations.AddField(
            model_name="flightinstance",
            name="departure_vertiport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departure_vertiport_flight_instances",
                to="monitor.vertiport",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="arrival_vertiport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="arrival_vertiport_routes",
                to="monitor.vertiport",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="departure_vertiport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departure_vertiport_routes",
                to="monitor.vertiport",
            ),
        ),
        migrations.AddField(
            model_name="waypoint",
            name="vertiport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vertiport_waypoints",
                to="monitor.vertiport",
            ),
        ),
    ]
