# Generated by Django 5.2.6 on 2025-11-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_vertiport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="arrival_vertiport",
        ),
        migrations.RemoveField(
            model_name="route",
            name="departure_vertiport",
        ),
    ]
