# Generated by Django 5.2.6 on 2025-11-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_remove_route_arrival_vertiport_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aircraft",
            old_name="model",
            new_name="aircraft_type",
        ),
    ]
