# Generated by Django 5.2.6 on 2025-12-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_rename_model_aircraft_aircraft_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraftdata",
            name="aircraft",
        ),
        migrations.AddField(
            model_name="aircraftdata",
            name="flight_instance",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_instance_taircraft_data",
                to="monitor.flightinstance",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracking",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vertiport",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="vertiport",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
