# Generated by Django 5.2.6 on 2026-01-10 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0006_remove_aircraftdata_aircraft_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraftdata",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="aircraftdata",
            name="flight_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_points",
                to="monitor.flightinstance",
            ),
        ),
        migrations.AlterField(
            model_name="tracking",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
