# Generated by Django 5.2.6 on 2026-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0007_remove_aircraftdata_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="energy_fuel",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
