# Generated by Django 5.2.6 on 2026-01-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0008_aircraft_energy_fuel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="energy_fuel",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
